import './js/to-top-before-unload.js';
import './js/window-resize.js';
import './js/header.js';
import './js/render-support.js';
import './js/renderBestsellers.js';
import './js/render-categories.js';
import './js/render-book-info.js';
import './js/theme-toggle.js';
import './js/modal-auth.js';
import './js/firebase-auth.js';
import './js/addToLocalStorage.js';
import './js/scroll-to-top.js';
import './js/modal-team.js';
import './js/footer-toggle.js';
import './js/books-content-by-category.js';
// import './js/markup-top-books.js';
