import './js/theme-toggle';
// import './js/header';
// import './js/render-support';
// import './js/firebase-auth';
// import './js/modal-auth';
import './js/onRemoveClick.js';
import './js/renderShoppingList';
import './js/tui-pagination';
import './js/support-list.js';
import './js/header.js';
// import './js/modal-team';
// import './js/footer-toggle.js';
// import './js/window-resize';
